import React, { useState, useEffect } from 'react'
import { Loader,FormField, Card } from '../components';


const Home = () => {

const [loading, setloading] = useState(false);
const [allPosts, setAllPosts] = useState(null);


  return (
<section className="max-w-7xl mx-auto">
  <div >
<h1 className="font-extrabold text-[#222328] text-[32px]">The Community showcase</h1>
<p className="mt-2 text-[#666e75] text-[16px] maxx-w-[500px]">Browse through a collection of imaginative and visually stunnig images generated by DALL-E AI</p>
  </div>

</section>
  )
}

export default Home